### ISSUE TITLE
Still missing all the design patterns

### ISSUE THREAD

**Issue by typesafeui** [maxdemaio/design-patterns#1]
You could use this book:
![51JYkEpbhzL](https://github.com/maxdemaio/design-patterns/assets/135900154/3289075a-eecc-4e8c-b4df-90de3c69e94c)

**Comment by juan7732** [comment]
Bump

**Comment by maxdemaio** [comment]
![image](https://github.com/maxdemaio/design-patterns/assets/44373521/2292d034-1c27-4c93-a014-c2f701b3095a)

**Comment by maxdemaio** [comment]
Dw, let me cook

**Comment by maxdemaio** [comment]
I finished them
